In [1]:
# CarDekho Price Prediction

# Importing Chennai Cars
import pandas as pd
chennai_cars=pd.read_excel("C:\\Users\\DELL\\Downloads\\chennai_cars.xlsx")

In [2]:
chennai_cars

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [3]:
chennai_cars['new_car_detail'][0]#['it']

"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '20,000', 'transmission': 'Automatic', 'ownerNo': 1, 'owner': '1st Owner', 'oem': 'Kia', 'model': 'Kia Sonet', 'modelYear': 2022, 'centralVariantId': 8654, 'variantName': 'Turbo DCT Anniversary Edition', 'price': 'â‚¹ 11.50 Lakh', 'priceActual': '', 'priceSaving': '', 'priceFixedText': None, 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg', 'heading': 'Trending Car!', 'desc': 'High chances of sale in next 6 days'}}"

In [4]:
import ast  # For evaluating the string representation of dictionaries

# Convert string representation of dictionaries to actual dictionaries
chennai_cars['new_car_detail'] = chennai_cars['new_car_detail'].apply(ast.literal_eval)

# Normalize the 'new_car_detail' column into separate columns
chennai_cars_normalized = pd.json_normalize(chennai_cars['new_car_detail'])

# Concatenate the normalized columns with the original DataFrame
chennai_cars_df = pd.concat([chennai_cars, chennai_cars_normalized], axis=1)

# Drop the original 'new_car_detail' column
chennai_cars_df = chennai_cars_df.drop('new_car_detail', axis=1)

In [5]:
chennai_cars['new_car_detail'][0]#['it']#['trendingText']['imgUrl']

{'it': 0,
 'ft': 'Petrol',
 'bt': 'SUV',
 'km': '20,000',
 'transmission': 'Automatic',
 'ownerNo': 1,
 'owner': '1st Owner',
 'oem': 'Kia',
 'model': 'Kia Sonet',
 'modelYear': 2022,
 'centralVariantId': 8654,
 'variantName': 'Turbo DCT Anniversary Edition',
 'price': 'â‚¹ 11.50 Lakh',
 'priceActual': '',
 'priceSaving': '',
 'priceFixedText': None,
 'trendingText': {'imgUrl': 'https://stimg.cardekho.com/used-cars/common/icons/trending.svg',
  'heading': 'Trending Car!',
  'desc': 'High chances of sale in next 6 days'}}

In [6]:
chennai_cars_df.head(2)

,new_car_overview,new_car_feature,new_car_specs,car_links,it,ft,bt,km,transmission,ownerNo,...,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Automatic,1,...,2022,8654,Turbo DCT Anniversary Edition,â‚¹ 11.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Minivans,"20,687",Manual,1,...,2015,4025,7 Seater Standard BSIV,â‚¹ 4.15 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [7]:
# Convert string representation of dictionaries to actual dictionaries
chennai_cars_df['new_car_overview']=chennai_cars_df['new_car_overview'].apply(ast.literal_eval)

# Normalize the 'new_car_detail' column into separate columns
chennai_cars_normalized = pd.json_normalize(chennai_cars_df['new_car_overview'])

# Concatenate the normalized columns with the original DataFrame
chennai_cars_df = pd.concat([chennai_cars_df, chennai_cars_normalized], axis=1)

# Drop the original 'new_car_detail' column
chennai_cars_df = chennai_cars_df.drop('new_car_overview', axis=1)

In [8]:
chennai_cars_df.head(2)

,new_car_feature,new_car_specs,car_links,it,ft,bt,km,transmission,ownerNo,owner,...,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,heading,top,bottomData
0,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,...,â‚¹ 11.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Car overview,"[{'key': 'Registration Year', 'value': '2022',...",None
1,"{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,...,â‚¹ 4.15 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None

In [9]:
# For checking purpose
chennai_cars_df['top'][0][0]['icon']#['key']#['value']['icon']

'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'

In [10]:
# Creating a new Dataframe to store required values
chennai_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        chennai_df_1["Car_Info"].append(key)
        chennai_df_1["Values_for_Car_Info"].append(values)
        chennai_df_1["Image_link_of_car"].append(icon)

# Convert the dictionary to a DataFrame
chennai_df_1 = pd.DataFrame(chennai_df_1)

In [11]:
chennai_df_1.head(5)

,Car_Info,Values_for_Car_Info,Image_link_of_car
0,Registration Year,2022,https://images10.gaadi.com/listing/vdp/co/v1/r...
1,Insurance Validity,Third Party insurance,https://images10.gaadi.com/listing/vdp/co/v1/i...
2,Fuel Type,Petrol,https://images10.gaadi.com/listing/vdp/co/v1/f...
3,Seats,5 Seats,https://images10.gaadi.com/listing/vdp/co/v1/s...
4,Kms Driven,"20,000 Kms",https://images10.gaadi.com/listing/vdp/co/v1/k...

In [12]:
chennai_cars_df = chennai_cars_df.drop(['top'], axis=1)
chennai_cars_df = chennai_cars_df.drop(['bottomData','heading'], axis=1)

In [13]:
# Convert string representation of dictionaries to actual dictionaries
chennai_cars_df['new_car_feature']=chennai_cars_df['new_car_feature'].apply(ast.literal_eval)

# Normalize the 'new_car_detail' column into separate columns
chennai_cars_normalized = pd.json_normalize(chennai_cars_df['new_car_feature'])

# Concatenate the normalized columns with the original DataFrame
chennai_cars_df = pd.concat([chennai_cars_df, chennai_cars_normalized], axis=1)

# Drop the original 'new_car_detail' column
chennai_cars_df = chennai_cars_df.drop('new_car_feature', axis=1)

In [14]:
chennai_cars_df.head(2)

,new_car_specs,car_links,it,ft,bt,km,transmission,ownerNo,owner,oem,...,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,heading,top,data,commonIcon
0,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,"[{'value': 'Low Fuel Warning Light'}, {'value'...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [15]:
# For checking purpose
chennai_cars_df['top']#[0]['value']

0       [{'value': 'Power Steering'}, {'value': 'Power...
1       [{'value': 'Low Fuel Warning Light'}, {'value'...
2       [{'value': 'Power Steering'}, {'value': 'Power...
3       [{'value': 'Power Steering'}, {'value': 'Power...
4       [{'value': 'Power Steering'}, {'value': 'Power...
                              ...
1414    [{'value': 'Power Steering'}, {'value': 'Power...
1415    [{'value': 'Power Steering'}, {'value': 'Power...
1416    [{'value': 'Power Steering'}, {'value': 'Power...
1417    [{'value': 'Power Steering'}, {'value': 'Power...
1418    [{'value': 'Power Steering'}, {'value': 'Power...
Name: top, Length: 1419, dtype: object

In [16]:
# Creating a new Dataframe to store required values
chennai_df_2 = { "Features": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        chennai_df_2["Features"].append(values)

# Convert the dictionary to a DataFrame
chennai_df_2 = pd.DataFrame(chennai_df_2)

In [17]:
chennai_df_2.head(2)

              Features
0       Power Steering
1  Power Windows Front

In [18]:
# For checking purpose
chennai_cars_df['data'][0]#['list'][0]

[{'heading': 'Comfort & Convenience',
  'subHeading': 'Comfort',
  'list': [{'value': 'Power Steering'},
   {'value': 'Power Windows Front'},
   {'value': 'Power Windows Rear'},
   {'value': 'Low Fuel Warning Light'},
   {'value': 'Accessory Power Outlet'},
   {'value': 'Trunk Light'},
   {'value': 'Rear Reading Lamp'},
   {'value': 'Rear Seat Headrest'},
   {'value': 'Rear Seat Centre Arm Rest'},
   {'value': 'Cup Holders Rear'},
   {'value': 'Multifunction Steering Wheel'},
   {'value': 'Cruise Control'},
   {'value': 'Rear ACVents'},
   {'value': 'Smart Access Card Entry'},
   {'value': 'Engine Start Stop Button'},
   {'value': 'Steering Wheel Gearshift Paddles'},
   {'value': 'Battery Saver'},
   {'value': 'Drive Modes'},
   {'value': 'Remote Engine Start Stop'},
   {'value': 'Adjustable Headrest'}]},
 {'heading': 'Interior',
  'subHeading': 'Interior',
  'list': [{'value': 'Air Conditioner'},
   {'value': 'Heater'},
   {'value': 'Adjustable Steering'},
   {'value': 'Digital Odometer'},
   {'value': 'Electronic Multi Tripmeter'},
   {'value': 'Leather Seats'},
   {'value': 'Fabric Upholstery'},
   {'value': 'Leather Steering Wheel'},
   {'value': 'Glove Compartment'},
   {'value': 'Digital Clock'},
   {'value': 'Driving Experience Control Eco'},
   {'value': 'Height Adjustable Driver Seat'},
   {'value': 'Leather Wrap Gear Shift Selector'}]},
 {'heading': 'Exterior',
  'subHeading': 'Exterior',
  'list': [{'value': 'Adjustable Head Lights'},
   {'value': 'Fog Lights Front'},
   {'value': 'Power Adjustable Exterior Rear View Mirror'},
   {'value': 'Electric Folding Rear View Mirror'},
   {'value': 'Rear Window Defogger'},
   {'value': 'Alloy Wheels'},
   {'value': 'Integrated Antenna'},
   {'value': 'Tinted Glass'},
   {'value': 'Rear Spoiler'},
   {'value': 'Sun Roof'},
   {'value': 'Moon Roof'},
   {'value': 'Outside Rear View Mirror Turn Indicators'},
   {'value': 'Chrome Grille'},
   {'value': 'Roof Rail'},
   {'value': 'LEDDRLs'},
   {'value': 'LEDHeadlights'},
   {'value': 'LEDTaillights'}]},
 {'heading': 'Safety',
  'subHeading': 'Safety',
  'list': [{'value': 'Anti Lock Braking System'},
   {'value': 'Brake Assist'},
   {'value': 'Centeral Locking'},
   {'value': 'Power Door Locks'},
   {'value': 'Child Safety Locks'},
   {'value': 'Driver Air Bag'},
   {'value': 'Passenger Air Bag'},
   {'value': 'Side Air Bag Front'},
   {'value': 'Day Night Rear View Mirror'},
   {'value': 'Passenger Side Rear View Mirror'},
   {'value': 'Rear Seat Belts'},
   {'value': 'Seat Belt Warning'},
   {'value': 'Vehicle Stability Control System'},
   {'value': 'Traction Control'},
   {'value': 'Adjustable Seats'},
   {'value': 'Keyless Entry'},
   {'value': 'Engine Check Warning'},
   {'value': 'Crash Sensor'},
   {'value': 'Automatic Head Lamps'},
   {'value': 'Ebd'},
   {'value': 'Follow Me Home Headlamps'},
   {'value': 'Rear Camera'},
   {'value': 'Anti Pinch Power Windows'},
   {'value': 'Speed Sensing Auto Door Lock'},
   {'value': 'Isofix Child Seat Mounts'},
   {'value': 'Pretensioners And Force Limiter Seatbelts'},
   {'value': 'Hill Assist'},
   {'value': 'Impact Sensing Auto Door Lock'},
   {'value': 'No Of Airbags'},
   {'value': 'Eletronic Stability Control'}]},
 {'heading': 'Entertainment & Communication',
  'subHeading': 'Entertainment',
  'list': [{'value': 'Radio'},
   {'value': 'Speakers Front'},
   {'value': 'Speakers Rear'},
   {'value': 'Integrated2Din Audio'},
   {'value': 'Bluetooth'},
   {'value': 'Touch Screen'},
   {'value': 'Number Of Speaker'},
   {'value': 'Apple Car Play'},
   {'value': 'Android Auto'}]}]

In [19]:
# Creating a new Dataframe to store required values
chennai_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        chennai_df_3["Comfort_and_Convenience"].append(heading)
        chennai_df_3["Comfort_and_Convenience_type"].append(values)

# Convert the dictionary to a DataFrame
chennai_df_3 = pd.DataFrame(chennai_df_3)

In [20]:
chennai_df_3.head(2)

  Comfort_and_Convenience Comfort_and_Convenience_type
0   Comfort & Convenience               Power Steering
1                Interior              Air Conditioner

In [21]:
# Drop the original 'new_car_detail' column
chennai_cars_df = chennai_cars_df.drop(['top','data'], axis=1)

In [22]:
# Convert string representation of dictionaries to actual dictionaries
chennai_cars_df['new_car_specs']=chennai_cars_df['new_car_specs'].apply(ast.literal_eval)

# Normalize the 'new_car_detail' column into separate columns
chennai_cars_normalized = pd.json_normalize(chennai_cars_df['new_car_specs'])

# Concatenate the normalized columns with the original DataFrame
chennai_cars_df = pd.concat([chennai_cars_df, chennai_cars_normalized], axis=1)

# Drop the original 'new_car_detail' column
chennai_cars_df = chennai_cars_df.drop('new_car_specs', axis=1)

In [23]:
chennai_cars_df.head(2)

,car_links,it,ft,bt,km,transmission,ownerNo,owner,oem,model,...,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,heading,commonIcon,heading,top,data,commonIcon
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,...,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Engine', 'value': '998 CC'}, {'key':...","[{'heading': 'Engine and Transmission', 'subHe...",
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,...,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Mileage', 'value': '15.37 kmpl'}, {'...","[{'heading': 'Engine and Transmission', 'subHe...",

In [24]:
# For checking purpose
chennai_cars_df['top'][0]#[0]['value']#[0]['list'][0]['value']

[{'key': 'Engine', 'value': '998 CC'},
 {'key': 'Max Power', 'value': '118.36bhp'},
 {'key': 'Torque', 'value': '172nm'},
 {'key': 'Wheel Size', 'value': '16'},
 {'key': 'Seats', 'value': '5'}]

In [25]:
# Creating a new Dataframe to store required values
chennai_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in chennai_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        chennai_df_4["Car_Specifications"].append(key)
        chennai_df_4["Values_for_Car_Specifications"].append(values)

# Convert the dictionary to a DataFrame
chennai_df_4 = pd.DataFrame(chennai_df_4)

In [26]:
chennai_df_4.head(3)

  Car_Specifications Values_for_Car_Specifications
0             Engine                        998 CC
1          Max Power                     118.36bhp
2             Torque                         172nm

In [27]:

# For checking purpose
chennai_cars_df['data'][0]#[0]['list'][0]['value']

[{'heading': 'Engine and Transmission',
  'subHeading': 'Engine',
  'list': [{'key': 'Color', 'value': 'Black'},
   {'key': 'Engine Type', 'value': 'Smartstream G1.0 T - GDi'},
   {'key': 'Displacement', 'value': '998'},
   {'key': 'Max Power', 'value': '118.36bhp@6000rpm'},
   {'key': 'Max Torque', 'value': '172nm@1500-4000rpm'},
   {'key': 'No of Cylinder', 'value': 3},
   {'key': 'Values per Cylinder', 'value': 4},
   {'key': 'Fuel Suppy System', 'value': 'GDi'},
   {'key': 'Turbo Charger', 'value': 'Yes'}]},
 {'heading': 'Dimensions & Capacity',
  'subHeading': 'Dimensions',
  'list': [{'key': 'Length', 'value': '3995mm'},
   {'key': 'Width', 'value': '1790'},
   {'key': 'Height', 'value': '1642'},
   {'key': 'Wheel Base', 'value': '2500'},
   {'key': 'Kerb Weight', 'value': '1465'}]},
 {'heading': 'Miscellaneous',
  'subHeading': 'Miscellaneous',
  'list': [{'key': 'Gear Box', 'value': '7-Speed DCT'},
   {'key': 'Drive Type', 'value': 'FWD'},
   {'key': 'Seating Capacity', 'value': '5'},
   {'key': 'Steering Type', 'value': 'Electric'},
   {'key': 'Front Brake Type', 'value': 'Disc'},
   {'key': 'Rear Brake Type', 'value': 'Drum'},
   {'key': 'Tyre Type', 'value': 'Tubeless, Radial'},
   {'key': 'Alloy Wheel Size', 'value': '16'},
   {'key': 'No Door Numbers', 'value': '5'},
   {'key': 'Cargo Volumn', 'value': '392'}]}]

In [28]:
# Creating a new Dataframe to store required values
chennai_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in chennai_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        chennai_df_5["Feature_heading"].append(heading)
        chennai_df_5["Feature_key_heading"].append(key)
        chennai_df_5["Feature_value"].append(values)

# Convert the dictionary to a DataFrame
chennai_df_5 = pd.DataFrame(chennai_df_5)

In [29]:
chennai_df_5.head(2)

  Feature_heading Feature_key_heading Feature_value
0          Engine               Color         Black
1      Dimensions              Length        3995mm

In [30]:
# Drop the original 'new_car_detail' column
chennai_cars_df = chennai_cars_df.drop(['top','data'], axis=1)

In [31]:
chennai_cars_df.head(2)

,car_links,it,ft,bt,km,transmission,ownerNo,owner,oem,model,...,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc,heading,commonIcon,heading,commonIcon
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,

In [32]:
print("chennai_cars_df columns:", chennai_cars_df.columns)
print("chennai_df_1 columns:", chennai_df_1.columns)
print("chennai_df_2 columns:", chennai_df_2.columns)
print("chennai_df_3 columns:", chennai_df_3.columns)
print("chennai_df_4 columns:", chennai_df_4.columns)
print("chennai_df_5 columns:", chennai_df_5.columns)

chennai_cars_df columns: Index(['car_links', 'it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner',
       'oem', 'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'commonIcon',
       'heading', 'commonIcon'],
      dtype='object')
chennai_df_1 columns: Index(['Car_Info', 'Values_for_Car_Info', 'Image_link_of_car'], dtype='object')
chennai_df_2 columns: Index(['Features'], dtype='object')
chennai_df_3 columns: Index(['Comfort_and_Convenience', 'Comfort_and_Convenience_type'], dtype='object')
chennai_df_4 columns: Index(['Car_Specifications', 'Values_for_Car_Specifications'], dtype='object')
chennai_df_5 columns: Index(['Feature_heading', 'Feature_key_heading', 'Feature_value'], dtype='object')

In [33]:
print("chennai_cars_df shape:", chennai_cars_df.shape)
print("chennai_df_1 shape:", chennai_df_1.shape)
print("chennai_df_2 shape:", chennai_df_2.shape)
print("chennai_df_3 shape:", chennai_df_3.shape)
print("chennai_df_4 shape:", chennai_df_4.shape)
print("chennai_df_5 shape:", chennai_df_5.shape)

chennai_cars_df shape: (1419, 24)
chennai_df_1 shape: (14036, 3)
chennai_df_2 shape: (12461, 1)
chennai_df_3 shape: (6865, 2)
chennai_df_4 shape: (7980, 2)
chennai_df_5 shape: (4251, 3)

In [34]:
# Merging all DataFrames

# Merge chennai_df_1 with chennai_cars_df
chennai_cars_df = pd.merge(chennai_cars_df, chennai_df_1, how='left', left_index=True, right_index=True)

# Merge chennai_df_2 with chennai_cars_df
chennai_cars_df = pd.merge(chennai_cars_df, chennai_df_2, how='left', left_index=True, right_index=True)

# Merge chennai_df_3 with chennai_cars_df
chennai_cars_df = pd.merge(chennai_cars_df, chennai_df_3, how='left', left_index=True, right_index=True)

# Merge chennai_df_4 with chennai_cars_df
chennai_cars_df = pd.merge(chennai_cars_df, chennai_df_4, how='left', left_index=True, right_index=True)

# Merge chennai_df_5 with chennai_cars_df
chennai_cars_df = pd.merge(chennai_cars_df, chennai_df_5, how='left', left_index=True, right_index=True)

In [35]:
chennai_cars_df.shape

(1419, 35)

In [36]:
chennai_cars_df.columns

Index(['car_links', 'it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner',
       'oem', 'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'commonIcon',
       'heading', 'commonIcon', 'Car_Info', 'Values_for_Car_Info',
       'Image_link_of_car', 'Features', 'Comfort_and_Convenience',
       'Comfort_and_Convenience_type', 'Car_Specifications',
       'Values_for_Car_Specifications', 'Feature_heading',
       'Feature_key_heading', 'Feature_value'],
      dtype='object')

In [37]:
import pandas as pd

# Assuming you have a DataFrame named chennai_cars_df

# Define a dictionary mapping current column names to new names
column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'
}

# Rename columns in chennai_cars_df
chennai_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [38]:
chennai_cars_df.isnull().sum()/len(chennai_cars_df)*100

car_links                            0.0
Ignition_type                        0.0
Fuel_type                            0.0
Body_type                            0.0
Kilometers_driven                    0.0
Transmission_type                    0.0
Number_of_previous_owners            0.0
Ownership_details                    0.0
Original_Equipment_Manufacturer      0.0
Car_model                            0.0
Year_of_car_manufacture              0.0
Central_variant_ID                   0.0
Variant_name                         0.0
Price_of_the_used_car                0.0
Actual_price                         0.0
Price_saving_information             0.0
Fixed price details                100.0
Image_URL                            0.0
Trending_heading                     0.0
Trending_description                 0.0
heading                              0.0
commonIcon                           0.0
heading                              0.0
commonIcon                           0.0
Car_Info                             0.0
Values_for_Car_Info                  0.0
Image_link_of_car                    0.0
Features                             0.0
Comfort_and_Convenience              0.0
Comfort_and_Convenience_type         0.0
Car_Specifications                   0.0
Values_for_Car_Specifications        0.0
Feature_heading                      0.0
Feature_key_heading                  0.0
Feature_value                        0.0
dtype: float64

In [39]:
chennai_cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1419 entries, 0 to 1418
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   car_links                        1419 non-null   object
 1   Ignition_type                    1419 non-null   int64
 2   Fuel_type                        1419 non-null   object
 3   Body_type                        1419 non-null   object
 4   Kilometers_driven                1419 non-null   object
 5   Transmission_type                1419 non-null   object
 6   Number_of_previous_owners        1419 non-null   int64
 7   Ownership_details                1419 non-null   object
 8   Original_Equipment_Manufacturer  1419 non-null   object
 9   Car_model                        1419 non-null   object
 10  Year_of_car_manufacture          1419 non-null   int64
 11  Central_variant_ID               1419 non-null   int64
 12  Variant_name                     1419 non-null   object
 13  Price_of_the_used_car            1419 non-null   object
 14  Actual_price                     1419 non-null   object
 15  Price_saving_information         1419 non-null   object
 16  Fixed price details              0 non-null      object
 17  Image_URL                        1419 non-null   object
 18  Trending_heading                 1419 non-null   object
 19  Trending_description             1419 non-null   object
 20  heading                          1419 non-null   object
 21  commonIcon                       1419 non-null   object
 22  heading                          1419 non-null   object
 23  commonIcon                       1419 non-null   object
 24  Car_Info                         1419 non-null   object
 25  Values_for_Car_Info              1419 non-null   object
 26  Image_link_of_car                1419 non-null   object
 27  Features                         1419 non-null   object
 28  Comfort_and_Convenience          1419 non-null   object
 29  Comfort_and_Convenience_type     1419 non-null   object
 30  Car_Specifications               1419 non-null   object
 31  Values_for_Car_Specifications    1419 non-null   object
 32  Feature_heading                  1419 non-null   object
 33  Feature_key_heading              1419 non-null   object
 34  Feature_value                    1419 non-null   object
dtypes: int64(4), object(31)
memory usage: 388.1+ KB

In [40]:
chennai_cars_df.head(10)

,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,...,Values_for_Car_Info,Image_link_of_car,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,...,2022,https://images10.gaadi.com/listing/vdp/co/v1/r...,Power Steering,Comfort & Convenience,Power Steering,Engine,998 CC,Engine,Color,Black
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,...,Third Party insurance,https://images10.gaadi.com/listing/vdp/co/v1/i...,Power Windows Front,Interior,Air Conditioner,Max Power,118.36bhp,Dimensions,Length,3995mm
2,https://www.cardekho.com/used-car-details/used...,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,...,Petrol,https://images10.gaadi.com/listing/vdp/co/v1/f...,Air Conditioner,Exterior,Adjustable Head Lights,Torque,172nm,Miscellaneous,Gear Box,7-Speed DCT
3,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,...,5 Seats,https://images10.gaadi.com/listing/vdp/co/v1/s...,Heater,Safety,Anti Lock Braking System,Wheel Size,16,Engine,Color,Grey
4,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,...,"20,000 Kms",https://images10.gaadi.com/listing/vdp/co/v1/k...,Adjustable Head Lights,Entertainment & Communication,Radio,Seats,5,Dimensions,Length,3675mm
5,https://www.cardekho.com/used-car-details/used...,0,Diesel,Sedan,"20,000",Automatic,1,1st Owner,Mercedes-Benz,Mercedes-Benz E-Class,...,TN02,https://images10.gaadi.com/listing/vdp/co/v1/r...,Fog Lights Front,Comfort & Convenience,Low Fuel Warning Light,Mileage,15.37 kmpl,Miscellaneous,Gear Box,5 Speed
6,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,Hatchback,"29,403",Automatic,1,1st Owner,Maruti,Maruti Celerio,...,First Owner,https://images10.gaadi.com/listing/vdp/co/v1/o...,Anti Lock Braking System,Interior,Heater,Engine,1196 CC,Engine,Color,Others
7,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"42,700",Manual,1,1st Owner,Maruti,Maruti A-Star,...,998 cc,https://images10.gaadi.com/listing/vdp/co/v1/e...,Brake Assist,Exterior,Adjustable Head Lights,Max Power,73bhp,Dimensions,Length,3994mm
8,https://www.cardekho.com/used-car-details/used...,0,Diesel,SUV,"23,001",Automatic,1,1st Owner,BMW,BMW X3,...,Automatic,https://images10.gaadi.com/listing/vdp/co/v1/t...,Radio,Safety,Anti Lock Braking System,Torque,101Nm,Miscellaneous,Gear Box,5 Speed
9,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"25,925",Automatic,2,2nd Owner,Ford,Ford Ecosport,...,2022,https://images10.gaadi.com/listing/vdp/co/v1/y...,Low Fuel Warning Light,Comfort & Convenience,Power Steering,Seats,7,Engine,Color,Silver

In [41]:
chennai_cars_df.columns

Index(['car_links', 'Ignition_type', 'Fuel_type', 'Body_type',
       'Kilometers_driven', 'Transmission_type', 'Number_of_previous_owners',
       'Ownership_details', 'Original_Equipment_Manufacturer', 'Car_model',
       'Year_of_car_manufacture', 'Central_variant_ID', 'Variant_name',
       'Price_of_the_used_car', 'Actual_price', 'Price_saving_information',
       'Fixed price details', 'Image_URL', 'Trending_heading',
       'Trending_description', 'heading', 'commonIcon', 'heading',
       'commonIcon', 'Car_Info', 'Values_for_Car_Info', 'Image_link_of_car',
       'Features', 'Comfort_and_Convenience', 'Comfort_and_Convenience_type',
       'Car_Specifications', 'Values_for_Car_Specifications',
       'Feature_heading', 'Feature_key_heading', 'Feature_value'],
      dtype='object')

In [42]:
url_links_chennai=chennai_cars_df[['car_links','Image_link_of_car']]

In [43]:
chennai_cars_df.drop(['car_links','Image_link_of_car'],axis=1,inplace=True)

In [44]:
chennai_cars_df.head(2)

,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,Year_of_car_manufacture,...,Car_Info,Values_for_Car_Info,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,Registration Year,2022,Power Steering,Comfort & Convenience,Power Steering,Engine,998 CC,Engine,Color,Black
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,Insurance Validity,Third Party insurance,Power Windows Front,Interior,Air Conditioner,Max Power,118.36bhp,Dimensions,Length,3995mm

In [45]:
chennai_cars_df['city'] = 'Chennai'

In [93]:
chennai_cars_df.head(2)

,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,Year_of_car_manufacture,...,Values_for_Car_Info,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value,city
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,2022,Power Steering,Comfort & Convenience,Power Steering,Engine,998 CC,Engine,Color,Black,Chennai
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,Third Party insurance,Power Windows Front,Interior,Air Conditioner,Max Power,118.36bhp,Dimensions,Length,3995mm,Chennai

In [94]:
chennai_cars_df.to_excel('Final_chennai_cars_list.xlsx')

In [95]:
chennai_cars_df.shape

(1419, 34)

In [48]:
# Importing Banglore Cars
blr_cars=pd.read_excel("C:\\Users\\DELL\\Downloads\\bangalore_cars.xlsx")

In [49]:
blr_cars.head(2)

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...

In [50]:
def json_normalize(df, column_name):
    import ast
    df[column_name] = df[column_name].apply(ast.literal_eval)
    df_normalized = pd.json_normalize(df[column_name])
    df_1 = pd.concat([df, df_normalized], axis=1)
    df_1 = df_1.drop(column_name, axis=1)
    return df_1

blr_cars_df = json_normalize(blr_cars, 'new_car_detail')

In [51]:
blr_cars_df.head(2)

,new_car_overview,new_car_feature,new_car_specs,car_links,it,ft,bt,km,transmission,ownerNo,...,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,...,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,...,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [52]:
def rename_columns(df, column_rename_mapping):
    column_rename_mapping = {
    'it': 'Ignition_type',
    'ft': 'Fuel_type',
    'bt': 'Body_type',
    'km': 'Kilometers_driven',
    'transmission': 'Transmission_type',
    'ownerNo': 'Number_of_previous_owners',
    'owner': 'Ownership_details',
    'oem': 'Original_Equipment_Manufacturer',
    'model': 'Car_model',
    'modelYear': 'Year_of_car_manufacture',
    'centralVariantId': 'Central_variant_ID',
    'variantName': 'Variant_name',
    'price': 'Price_of_the_used_car',
    'priceActual': 'Actual_price',
    'priceSaving': 'Price_saving_information',
    'priceFixedText': 'Fixed price details',
    'trendingText.imgUrl': 'Image_URL',
    'trendingText.heading': 'Trending_heading',
    'trendingText.desc': 'Trending_description'}
    df.rename(columns=column_rename_mapping, inplace=True)
    return df

# Rename columns in banglore_cars_df
blr_cars_df.rename(columns=column_rename_mapping, inplace=True)

In [53]:
blr_cars_df.head(2)

,new_car_overview,new_car_feature,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,...,Year_of_car_manufacture,Central_variant_ID,Variant_name,Price_of_the_used_car,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description
0,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,...,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,"{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,...,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [54]:
blr_cars_df = json_normalize(blr_cars_df, 'new_car_overview')

In [55]:
blr_cars_df.head(2)

,new_car_feature,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,...,Price_of_the_used_car,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,top,bottomData
0,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,...,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,...,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None

In [56]:
# For checking purpose
blr_cars_df['top'][0][0]#['icon']#['key']#['value']['icon']

{'key': 'Registration Year',
 'value': '2015',
 'icon': 'https://images10.gaadi.com/listing/vdp/co/v1/registrationYear.svg'}

In [57]:
# Creating a new Dataframe to store required values
blr_df_1 = {"Car_Info": [], "Values_for_Car_Info": [], "Image_link_of_car": []}

for index, row in blr_cars_df.iterrows():
    for item in row['top']:
        key = item['key']
        values = item['value']
        icon = item['icon']
        blr_df_1["Car_Info"].append(key)
        blr_df_1["Values_for_Car_Info"].append(values)
        blr_df_1["Image_link_of_car"].append(icon)

# Convert the dictionary to a DataFrame
blr_df_1 = pd.DataFrame(blr_df_1)

In [58]:
blr_df_1.head(2)

,Car_Info,Values_for_Car_Info,Image_link_of_car
0,Registration Year,2015,https://images10.gaadi.com/listing/vdp/co/v1/r...
1,Insurance Validity,Third Party insurance,https://images10.gaadi.com/listing/vdp/co/v1/i...

In [59]:
blr_cars_df.head(2)

,new_car_feature,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,...,Price_of_the_used_car,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,top,bottomData
0,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,...,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Car overview,"[{'key': 'Registration Year', 'value': '2015',...",None
1,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,...,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Car overview,"[{'key': 'Registration Year', 'value': 'Feb 20...",None

In [60]:
blr_cars_df = blr_cars_df.drop(['top'], axis=1)

In [61]:
blr_cars_df = blr_cars_df.drop(['bottomData','heading'], axis=1)

In [62]:
blr_cars_df.head(2)

,new_car_feature,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,...,Year_of_car_manufacture,Central_variant_ID,Variant_name,Price_of_the_used_car,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description
0,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,...,2015,3979,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,"{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,...,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [63]:
blr_cars_df = json_normalize(blr_cars_df, 'new_car_feature')

In [64]:
blr_cars_df.head(2)

,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,...,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,top,data,commonIcon
0,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [65]:
# Creating a new Dataframe to store required values
blr_df_2 = { "Features": []}

for index, row in blr_cars_df.iterrows():
    for item in row['top']:
        values = item['value']
        blr_df_2["Features"].append(values)

# Convert the dictionary to a DataFrame
blr_df_2 = pd.DataFrame(blr_df_2)

In [66]:
blr_df_2.head(2)

              Features
0       Power Steering
1  Power Windows Front

In [67]:
# Creating a new Dataframe to store required values
blr_df_3 = {"Comfort_and_Convenience": [], "Comfort_and_Convenience_type": []}

for index, row in blr_cars_df.iterrows():
    for item in row['data']:
        heading = item['heading']
        values = item['list'][0]['value']
        blr_df_3["Comfort_and_Convenience"].append(heading)
        blr_df_3["Comfort_and_Convenience_type"].append(values)

# Convert the dictionary to a DataFrame
blr_df_3 = pd.DataFrame(blr_df_3)

In [68]:
blr_df_3.head(2)

  Comfort_and_Convenience Comfort_and_Convenience_type
0   Comfort & Convenience               Power Steering
1                Interior              Air Conditioner

In [69]:
blr_cars_df.head(2)

,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,...,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,top,data,commonIcon
0,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [70]:
blr_cars_df=blr_cars_df.drop(['top','data'],axis=1)

In [71]:
blr_cars_df.head(2)

,new_car_specs,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,...,Variant_name,Price_of_the_used_car,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,commonIcon
0,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,...,VXI,â‚¹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1,"{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,...,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

In [72]:
blr_cars_df = json_normalize(blr_cars_df, 'new_car_specs')

In [73]:
blr_cars_df.head(2)

,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,...,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,commonIcon,heading,top,data,commonIcon
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,...,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,...,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",

In [74]:
# For checking purpose
blr_cars_df['top'][0]#[0]['list'][0]['value']

[{'key': 'Mileage', 'value': '23.1 kmpl'},
 {'key': 'Engine', 'value': '998 CC'},
 {'key': 'Max Power', 'value': '67.04bhp'},
 {'key': 'Torque', 'value': '90Nm'},
 {'key': 'Seats', 'value': '5'}]

In [75]:
# Creating a new Dataframe to store required values
blr_df_4 = {"Car_Specifications": [], "Values_for_Car_Specifications": []}

for index, row in blr_cars_df.iterrows():
    for item in row['top']:
        key=item['key']
        values = item['value']
        blr_df_4["Car_Specifications"].append(key)
        blr_df_4["Values_for_Car_Specifications"].append(values)

# Convert the dictionary to a DataFrame
blr_df_4 = pd.DataFrame(blr_df_4)

In [76]:
blr_df_4.head(2)

  Car_Specifications Values_for_Car_Specifications
0            Mileage                     23.1 kmpl
1             Engine                        998 CC

In [77]:
# For checking purpose
blr_cars_df['data'][0]#[0]['list'][0]['value']

[{'heading': 'Engine and Transmission',
  'subHeading': 'Engine',
  'list': [{'key': 'Color', 'value': 'White'},
   {'key': 'Engine Type', 'value': 'K10B Engine'},
   {'key': 'Displacement', 'value': '998'},
   {'key': 'Max Power', 'value': '67.04bhp@6000rpm'},
   {'key': 'Max Torque', 'value': '90Nm@3500rpm'},
   {'key': 'No of Cylinder', 'value': 3},
   {'key': 'Values per Cylinder', 'value': 4},
   {'key': 'Value Configuration', 'value': 'DOHC'},
   {'key': 'Fuel Suppy System', 'value': 'MPFi'},
   {'key': 'BoreX Stroke', 'value': '73 X 82 mm'},
   {'key': 'Compression Ratio', 'value': '11.0:1'},
   {'key': 'Turbo Charger', 'value': 'No'},
   {'key': 'Super Charger', 'value': 'No'}]},
 {'heading': 'Dimensions & Capacity',
  'subHeading': 'Dimensions',
  'list': [{'key': 'Length', 'value': '3715mm'},
   {'key': 'Width', 'value': '1635mm'},
   {'key': 'Height', 'value': '1565mm'},
   {'key': 'Wheel Base', 'value': '2425mm'},
   {'key': 'Front Tread', 'value': '1420mm'},
   {'key': 'Rear Tread', 'value': '1410mm'},
   {'key': 'Kerb Weight', 'value': '835kg'},
   {'key': 'Gross Weight', 'value': '1250kg'}]},
 {'heading': 'Miscellaneous',
  'subHeading': 'Miscellaneous',
  'list': [{'key': 'Gear Box', 'value': '5 Speed '},
   {'key': 'Drive Type', 'value': 'FWD'},
   {'key': 'Seating Capacity', 'value': '5'},
   {'key': 'Steering Type', 'value': 'Power'},
   {'key': 'Turning Radius', 'value': '4.7 metres'},
   {'key': 'Front Brake Type', 'value': 'Ventilated Disc'},
   {'key': 'Rear Brake Type', 'value': 'Drum'},
   {'key': 'Top Speed', 'value': '150 Kmph'},
   {'key': 'Acceleration', 'value': '15.05 Seconds'},
   {'key': 'Tyre Type', 'value': 'Tubeless, Radial'},
   {'key': 'No Door Numbers', 'value': '5'},
   {'key': 'Cargo Volumn', 'value': '235-litres'}]}]

In [78]:
# Creating a new Dataframe to store required values
blr_df_5 = {"Feature_heading": [], "Feature_key_heading": [],"Feature_value":[]}

for index, row in blr_cars_df.iterrows():
    for item in row['data']:
        heading = item['subHeading']
        key=item['list'][0]['key']
        values = item['list'][0]['value']
        blr_df_5["Feature_heading"].append(heading)
        blr_df_5["Feature_key_heading"].append(key)
        blr_df_5["Feature_value"].append(values)

# Convert the dictionary to a DataFrame
blr_df_5 = pd.DataFrame(blr_df_5)

In [79]:
blr_df_5.head(2)

  Feature_heading Feature_key_heading Feature_value
0          Engine               Color         White
1      Dimensions              Length        3715mm

In [80]:
blr_cars_df.head(2)

,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,...,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,commonIcon,heading,top,data,commonIcon
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,...,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...","[{'heading': 'Engine and Transmission', 'subHe...",
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,...,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Mileage', 'value': '17 kmpl'}, {'key...","[{'heading': 'Engine and Transmission', 'subHe...",

In [81]:
# Drop the top and data column
blr_cars_df = blr_cars_df.drop(['top','data'], axis=1)

In [82]:
blr_cars_df.head(2)

,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,...,Actual_price,Price_saving_information,Fixed price details,Image_URL,Trending_heading,Trending_description,heading,commonIcon,heading,commonIcon
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,...,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days,Features,https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,

In [83]:
# Merging all DataFrames

# Merge blr_df_1 with blr_cars_df
blr_cars_df = pd.merge(blr_cars_df, blr_df_1, how='left', left_index=True, right_index=True)

# Merge blr_df_2 with blr_cars_df
blr_cars_df = pd.merge(blr_cars_df, blr_df_2, how='left', left_index=True, right_index=True)

# Merge blr_df_3 with blr_cars_df
blr_cars_df = pd.merge(blr_cars_df, blr_df_3, how='left', left_index=True, right_index=True)

# Merge blr_df_4 with blr_cars_df
blr_cars_df = pd.merge(blr_cars_df, blr_df_4, how='left', left_index=True, right_index=True)

# Merge blr_df_5 with blr_cars_df
blr_cars_df = pd.merge(blr_cars_df, blr_df_5, how='left', left_index=True, right_index=True)

In [84]:
blr_cars_df.head(2)

,car_links,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,...,Values_for_Car_Info,Image_link_of_car,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value
0,https://www.cardekho.com/used-car-details/used...,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,...,2015,https://images10.gaadi.com/listing/vdp/co/v1/r...,Power Steering,Comfort & Convenience,Power Steering,Mileage,23.1 kmpl,Engine,Color,White
1,https://www.cardekho.com/buy-used-car-details/...,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,...,Third Party insurance,https://images10.gaadi.com/listing/vdp/co/v1/i...,Power Windows Front,Interior,Air Conditioner,Engine,998 CC,Dimensions,Length,3715mm

In [85]:
blr_cars_df.shape

(1481, 35)

In [86]:
blr_cars_df.columns

Index(['car_links', 'Ignition_type', 'Fuel_type', 'Body_type',
       'Kilometers_driven', 'Transmission_type', 'Number_of_previous_owners',
       'Ownership_details', 'Original_Equipment_Manufacturer', 'Car_model',
       'Year_of_car_manufacture', 'Central_variant_ID', 'Variant_name',
       'Price_of_the_used_car', 'Actual_price', 'Price_saving_information',
       'Fixed price details', 'Image_URL', 'Trending_heading',
       'Trending_description', 'heading', 'commonIcon', 'heading',
       'commonIcon', 'Car_Info', 'Values_for_Car_Info', 'Image_link_of_car',
       'Features', 'Comfort_and_Convenience', 'Comfort_and_Convenience_type',
       'Car_Specifications', 'Values_for_Car_Specifications',
       'Feature_heading', 'Feature_key_heading', 'Feature_value'],
      dtype='object')

In [87]:
url_links_blr=blr_cars_df[['car_links','Image_link_of_car']]

In [88]:
blr_cars_df=blr_cars_df.drop(['car_links','Image_link_of_car'],axis=1)

In [89]:
blr_cars_df['city']='Banglore'

In [90]:
blr_cars_df.head(2)

,Ignition_type,Fuel_type,Body_type,Kilometers_driven,Transmission_type,Number_of_previous_owners,Ownership_details,Original_Equipment_Manufacturer,Car_model,Year_of_car_manufacture,...,Values_for_Car_Info,Features,Comfort_and_Convenience,Comfort_and_Convenience_type,Car_Specifications,Values_for_Car_Specifications,Feature_heading,Feature_key_heading,Feature_value,city
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,2015,Power Steering,Comfort & Convenience,Power Steering,Mileage,23.1 kmpl,Engine,Color,White,Banglore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Third Party insurance,Power Windows Front,Interior,Air Conditioner,Engine,998 CC,Dimensions,Length,3715mm,Banglore

In [91]:
blr_cars_df.to_excel('Final_banglore_cars_list.xlsx')

In [92]:
blr_cars_df.shape

(1481, 34)